import { Injector } from "www/injector";
import { PostLineStep } from "www/__test__/testPost";
import { HasACardHighlightedAtHisHand } from "./HasACardHighlightedAtHisHand";
import { HasACardOfHighlightedAtHisHand } from "./HasACardOfHighlightedAtHisHand";
import { HasNoCardOfHighlightedAtHisHand } from "./HasNoCardOfHighlightedAtHisHand";
import { PicksACard } from "./PicksACard";
import { PicksACardOf } from "./PicksACardOf";
import { PicksFromHandACard } from "./PicksFromHandACard";
import { PlacesTheCardIntoThePile } from "./PlacesTheCardIntoThePile";
import { PlaysACardIntoHisSquarePile } from "./PlaysACardIntoHisSquarePile";
import { PlaysACardIntoTheSquarePile } from "./PlaysACardIntoTheSquarePile";
import { PlaysACardIntoThePile } from "./PlaysACardIntoThePile";
import { PlaysACardOfIntoHisSquarePile } from "./PlaysACardOfIntoHisSquarePile";
import { PlaysACardOfIntoThePile } from "./PlaysACardOfIntoThePile";
import { PlaysACardOfIntoTheSquarePile } from "./PlaysACardOfIntoTheSquarePile";
import { PlaysNCardsIntoHisSquarePile } from "./PlaysNCardsIntoHisSquarePile";
import { PlaysNCardsIntoThePile } from "./PlaysNCardsIntoThePile";
import { PlaysNCardsIntoTheSquarePile } from "./PlaysNCardsIntoTheSquarePile";
import { PlaysNCardsOfIntoHisSquarePile } from "./PlaysNCardsOfIntoHisSquarePile";
import { PlaysNCardsOfIntoThePile } from "./PlaysNCardsOfIntoThePile";
import { PlaysNCardsOfIntoTheSquarePile } from "./PlaysNCardsOfIntoTheSquarePile";
import { PlaysNNNCardsIntoThePile } from "./PlaysNNNCardsIntoThePile";
import { ThePileIsHighlighted } from "./ThePileIsHighlighted";
import { ThePileIsNotHighlighted } from "./ThePileIsNotHighlighted";
import { ThereAreNoCardsIntoSquarePile } from "./ThereAreNoCardsIntoSquarePile";
import { ThereAreNoHighlightedCards } from "./ThereAreNoHighlightedCards";
import { ThereAreNoHighlightedPiles } from "./ThereAreNoHighlightedPiles";
import { TheSquarePileIsHighlighted } from "./TheSquarePileIsHighlighted";
import { TheSquarePileIsNotHighlighted } from "./TheSquarePileIsNotHighlighted";

export default function configureTestStepsPlayInjector(injector: Injector) {
  injector.register(PostLineStep, HasACardHighlightedAtHisHand);
  injector.register(PostLineStep, HasACardOfHighlightedAtHisHand);
  injector.register(PostLineStep, HasNoCardOfHighlightedAtHisHand);
  injector.register(PostLineStep, PicksACard);
  injector.register(PostLineStep, PicksACardOf);
  injector.register(PostLineStep, PicksFromHandACard);
  injector.register(PostLineStep, PlacesTheCardIntoThePile);
  injector.register(PostLineStep, PlaysACardIntoHisSquarePile);
  injector.register(PostLineStep, PlaysACardIntoTheSquarePile);
  injector.register(PostLineStep, PlaysACardIntoThePile);
  injector.register(PostLineStep, PlaysACardOfIntoHisSquarePile);
  injector.register(PostLineStep, PlaysACardOfIntoThePile);
  injector.register(PostLineStep, PlaysACardOfIntoTheSquarePile);
  injector.register(PostLineStep, PlaysNCardsIntoHisSquarePile);
  injector.register(PostLineStep, PlaysNCardsIntoThePile);
  injector.register(PostLineStep, PlaysNCardsIntoTheSquarePile);
  injector.register(PostLineStep, PlaysNCardsOfIntoHisSquarePile);
  injector.register(PostLineStep, PlaysNCardsOfIntoThePile);
  injector.register(PostLineStep, PlaysNCardsOfIntoTheSquarePile);
  injector.register(PostLineStep, PlaysNNNCardsIntoThePile);
  injector.register(PostLineStep, ThePileIsHighlighted);
  injector.register(PostLineStep, ThePileIsNotHighlighted);
  injector.register(PostLineStep, ThereAreNoCardsIntoSquarePile);
  injector.register(PostLineStep, ThereAreNoHighlightedCards);
  injector.register(PostLineStep, ThereAreNoHighlightedPiles);
  injector.register(PostLineStep, TheSquarePileIsHighlighted);
  injector.register(PostLineStep, TheSquarePileIsNotHighlighted);
}
